export { tid } from "./tid.js";
export { spec, skip, isSkip } from "./spec.js";
export { defineConfig } from "./config.js";
export type {
  Matcher,
  MatcherResult,
  MatcherContext,
  TestContext,
  SpecConfig,
  SpecFn,
  SpecRegistration,
  BreakpointsOf,
  ComponentsOf,
} from "./types.js";
export type { Contract } from "./matchers.js";
export {
  all,
  not,
  nth,
  whenHovered,
  whenFocused,
  whenChecked,
  whenValid,
  whenDark,
  whenLight,
  whenReducedMotion,
  whenPrint,
  hasWidth,
  hasHeight,
  hasCSS,
  isAbove,
  isBelow,
  isLeftOf,
  isRightOf,
  isInside,
  doesNotOverlap,
  overlaps,
  hasGap,
  isAlignedWith,
  isCenteredIn,
  isCenteredHorizontallyIn,
  isCenteredVerticallyIn,
  isVisible,
  isHidden,
  isWiderThan,
  isNarrowerThan,
  isTallerThan,
  isShorterThan,
  isSameSizeAs,
  isFlushWith,
  isStackedAbove,
  isStackedBelow,
} from "./matchers.js";
